name=OO-Servo (ooservo)
version=1.0.0
author=tekuteru
maintainer=@gmail.com
sentence=Arduino Library for controlling OO-Servo
paragraph=
category=Device Control
url=https://github.com/あなたのGitHubユーザー名/ooservo
architectures=*
license=MIT